# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d621af5be92298bd9e333b3d31f88e69c2d36ace9c1475d8b3b955188b50fb878b3a92f3bc2b33eeccc57cd7cf71dcd62f2b6f105fb2473e4882e430245b9e32

test:
  secret_key_base: 7a5f8972b88968cb6e04f85b9a409d16c0bb4d7adeb638781df8beae3dd1510a7585dc6af72a414ce13650ba09c5d2e2666487b9e98cd37c69c78660337a05ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
